version: "3.9"
services:
  db:
    image: bitnami/postgresql:9.6.24
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=database_user
      - POSTGRES_PASSWORD=database_pass
    ports:
      - port:port
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  bot:
    build: .
    command: python src/main.py
    container_name: bot
    environment:
     - TOKEN=Token
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
     - PORT=port
     - HOST=db
     - DRIVER_PASSWORD=Driverpass
     - MANAGER_PASSWORD=Managerpass
    volumes:
      - .:/app
    depends_on:
      - db